"""empty message

Revision ID: 474e34411946
Revises: f04c70663f4e
Create Date: 2020-12-16 19:48:48.187254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '474e34411946'
down_revision = 'f04c70663f4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('genres', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'genres')
    # ### end Alembic commands ###
